spring:
  resources:
    chain:
      cache: false

  jpa:
    database: HSQL
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        hbm2ddl:
          import_files:
            database/initial-cidades.sql
        dialect: org.hibernate.dialect.HSQLDialect

  datasource:
    url:
    jdbcUrl: jdbc:hsqldb:mem:testdb
    username: sa
    password: sa
    driverClassName: org.hsqldb.jdbcDriver